/** @file     OsTask_100ms.c
  *
  * @brief    Task OsTask_100ms body
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE for Windows
  * @note     Version 12.5.0
  */

#define RTE_CORE

#include "Rte_Const.h"
#if !defined(RTE_VENDOR_MODE)
#pragma message "Compiling an individual task file but RTE_VENDOR_MODE not defined. Compiling a stale file?"
#endif /* !defined(RTE_VENDOR_MODE) */
#if defined(RTE_USE_TASK_HEADER)
#include "OsTask_100ms.h"
#else /* !defined(RTE_USE_TASK_HEADER) */
#include "Os.h"
#endif /* !defined(RTE_USE_TASK_HEADER) */
#if defined(RTE_REQUIRES_IOC)
#include "Ioc.h"
#endif /* defined(RTE_REQUIRES_IOC) */
#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_Type.h"
#include "Rte_DataHandleType.h"
#include "Rte_SampleAppB.h"

#define RTE_OSTASK_100MS_START_SEC_VAR_INIT_8
#include "Rte_MemMap.h"
extern VAR(uint8, RTE_DATA) Rte_RECount_OsTask_100ms_divby10_0;
#define RTE_OSTASK_100MS_STOP_SEC_VAR_INIT_8
#include "Rte_MemMap.h"

#define COM_START_SEC_CODE
#include "Com_MemMap.h"
/* Runnable entity prototypes */
FUNC(void, COM_CODE) Com_MainFunctionTx_ComMainFunctionTx(void);
#define COM_STOP_SEC_CODE
#include "Com_MemMap.h"

#define OS_START_SEC_CODE_OSTASK_100MS
#include "Os_MemMap.h"
TASK(OsTask_100ms)
{
   /* Box: Implicit Buffer Initialization begin */
   /* Box: Implicit Buffer Initialization end */
   /* Box: Implicit Buffer Fill begin */
   /* Box: Implicit Buffer Fill end */
   /* Box: BSWImpl6_Com begin */
   if ( Rte_RECount_OsTask_100ms_divby10_0 == ((VAR(uint8, AUTOMATIC))0U) )
   {
      /* Box: populateTask begin */
      Com_MainFunctionTx_ComMainFunctionTx();
      /* Box: populateTask end */
   }
   /* Box: BSWImpl6_Com end */
   {
      /* Box: SWCI17 begin */
      /* Box: populateTask begin */
      SampleAppB_Runnable_Implicit();
      /* Box: populateTask end */
      /* Box: SWCI17 end */
   }
   /* Box: Implicit Buffer Flush begin */
   /* Box: Implicit Buffer Flush end */
   if ( Rte_RECount_OsTask_100ms_divby10_0 != ((VAR(uint8, AUTOMATIC))0U) )
   {
      Rte_RECount_OsTask_100ms_divby10_0--;
   }
   else
   {
      Rte_RECount_OsTask_100ms_divby10_0 = ((VAR(uint8, AUTOMATIC))9);
   }
   TerminateTask();
} /* OsTask_100ms */
#define OS_STOP_SEC_CODE_OSTASK_100MS
#include "Os_MemMap.h"

