/** @file     OsTask_100ms.c
  *
  * @brief    Task OsTask_100ms body
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE for Windows
  * @note     Version 12.5.0
  */

#define RTE_CORE

#include "Rte_Const.h"
#if !defined(RTE_VENDOR_MODE)
#pragma message "Compiling an individual task file but RTE_VENDOR_MODE not defined. Compiling a stale file?"
#endif /* !defined(RTE_VENDOR_MODE) */
#if defined(RTE_USE_TASK_HEADER)
#include "OsTask_100ms.h"
#else /* !defined(RTE_USE_TASK_HEADER) */
#include "Os.h"
#endif /* !defined(RTE_USE_TASK_HEADER) */
#if defined(RTE_REQUIRES_IOC)
#include "Ioc.h"
#endif /* defined(RTE_REQUIRES_IOC) */
#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_Type.h"
#include "Rte_DataHandleType.h"
#include "Rte_SampleAppB.h"

#define RTE_ECUCPARTITION_0_START_SEC_VAR_CLEARED_32
#include "Rte_MemMap.h"
extern VAR(Rte_EcucPartition_0_ImplicitBufsType, RTE_DATA) Rte_EcucPartition_0_ImplicitBufs;
extern VAR(SampleApp_1kB_ArrayType, RTE_DATA) Rte_Rx_000016;
extern VAR(SampleApp_1kB_ArrayType, RTE_DATA) Rte_Rx_000017;
extern VAR(SampleApp_1kB_ArrayType, RTE_DATA) Rte_Rx_000018;
extern VAR(SampleApp_1kB_ArrayType, RTE_DATA) Rte_Rx_000019;
extern VAR(SampleApp_1kB_ArrayType, RTE_DATA) Rte_Rx_000020;
extern VAR(SampleApp_1kB_ArrayType, RTE_DATA) Rte_Rx_000021;
extern VAR(SampleApp_1kB_ArrayType, RTE_DATA) Rte_Rx_000022;
extern VAR(SampleApp_1kB_ArrayType, RTE_DATA) Rte_Rx_000023;
extern VAR(SampleApp_1kB_ArrayType, RTE_DATA) Rte_Rx_000024;
extern VAR(SampleApp_1kB_ArrayType, RTE_DATA) Rte_Rx_000025;
extern VAR(SampleApp_StructureType, RTE_DATA) Rte_Rx_000036;
extern VAR(SampleApp_StructureType, RTE_DATA) Rte_Rx_000037;
extern VAR(SampleApp_StructureType, RTE_DATA) Rte_Rx_000038;
extern VAR(SampleApp_StructureType, RTE_DATA) Rte_Rx_000039;
extern VAR(SampleApp_StructureType, RTE_DATA) Rte_Rx_000040;
extern VAR(SampleApp_StructureType, RTE_DATA) Rte_Rx_000041;
extern VAR(SampleApp_StructureType, RTE_DATA) Rte_Rx_000042;
extern VAR(SampleApp_StructureType, RTE_DATA) Rte_Rx_000043;
extern VAR(SampleApp_StructureType, RTE_DATA) Rte_Rx_000044;
extern VAR(SampleApp_StructureType, RTE_DATA) Rte_Rx_000045;
#define RTE_ECUCPARTITION_0_STOP_SEC_VAR_CLEARED_32
#include "Rte_MemMap.h"

#define RTE_ECUCPARTITION_0_START_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"
extern VAR(uint8, RTE_DATA) Rte_Rx_000026;
extern VAR(uint8, RTE_DATA) Rte_Rx_000027;
extern VAR(uint8, RTE_DATA) Rte_Rx_000028;
extern VAR(uint8, RTE_DATA) Rte_Rx_000029;
extern VAR(uint8, RTE_DATA) Rte_Rx_000030;
extern VAR(uint8, RTE_DATA) Rte_Rx_000031;
extern VAR(uint8, RTE_DATA) Rte_Rx_000032;
extern VAR(uint8, RTE_DATA) Rte_Rx_000033;
extern VAR(uint8, RTE_DATA) Rte_Rx_000034;
extern VAR(uint8, RTE_DATA) Rte_Rx_000035;
#define RTE_ECUCPARTITION_0_STOP_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"

#define RTE_OSTASK_100MS_START_SEC_VAR_INIT_8
#include "Rte_MemMap.h"
extern VAR(uint8, RTE_DATA) Rte_RECount_OsTask_100ms_divby10_0;
#define RTE_OSTASK_100MS_STOP_SEC_VAR_INIT_8
#include "Rte_MemMap.h"

#define COM_START_SEC_CODE
#include "Com_MemMap.h"
/* Runnable entity prototypes */
FUNC(void, COM_CODE) Com_MainFunctionTx_ComMainFunctionTx(void);
#define COM_STOP_SEC_CODE
#include "Com_MemMap.h"

#define OS_START_SEC_CODE_OSTASK_100MS
#include "Os_MemMap.h"
TASK(OsTask_100ms)
{
   /* Box: Implicit Buffer Initialization begin */
   /* Box: Implicit Buffer Initialization end */
   /* Box: Implicit Buffer Fill begin */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf0.value = Rte_Rx_000026;
   Rte_memcpy(Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf1.value, Rte_Rx_000016, sizeof(SampleApp_1kB_ArrayType));
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf2.value = Rte_Rx_000036;
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf3.value = Rte_Rx_000028;
   Rte_memcpy(Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf4.value, Rte_Rx_000018, sizeof(SampleApp_1kB_ArrayType));
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf5.value = Rte_Rx_000038;
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf6.value = Rte_Rx_000029;
   Rte_memcpy(Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf7.value, Rte_Rx_000019, sizeof(SampleApp_1kB_ArrayType));
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf8.value = Rte_Rx_000039;
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf9.value = Rte_Rx_000030;
   Rte_memcpy(Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf10.value, Rte_Rx_000020, sizeof(SampleApp_1kB_ArrayType));
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf11.value = Rte_Rx_000040;
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf12.value = Rte_Rx_000031;
   Rte_memcpy(Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf13.value, Rte_Rx_000021, sizeof(SampleApp_1kB_ArrayType));
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf14.value = Rte_Rx_000041;
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf15.value = Rte_Rx_000032;
   Rte_memcpy(Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf16.value, Rte_Rx_000022, sizeof(SampleApp_1kB_ArrayType));
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf17.value = Rte_Rx_000042;
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf18.value = Rte_Rx_000033;
   Rte_memcpy(Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf19.value, Rte_Rx_000023, sizeof(SampleApp_1kB_ArrayType));
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf20.value = Rte_Rx_000043;
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf21.value = Rte_Rx_000034;
   Rte_memcpy(Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf22.value, Rte_Rx_000024, sizeof(SampleApp_1kB_ArrayType));
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf23.value = Rte_Rx_000044;
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf24.value = Rte_Rx_000035;
   Rte_memcpy(Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf25.value, Rte_Rx_000025, sizeof(SampleApp_1kB_ArrayType));
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf26.value = Rte_Rx_000045;
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf27.value = Rte_Rx_000027;
   Rte_memcpy(Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf28.value, Rte_Rx_000017, sizeof(SampleApp_1kB_ArrayType));
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_8.Rte_OsTask_100ms.rbuf29.value = Rte_Rx_000037;
   /* Box: Implicit Buffer Fill end */
   /* Box: BSWImpl6_Com begin */
   if ( Rte_RECount_OsTask_100ms_divby10_0 == ((VAR(uint8, AUTOMATIC))0U) )
   {
      /* Box: populateTask begin */
      Com_MainFunctionTx_ComMainFunctionTx();
      /* Box: populateTask end */
   }
   /* Box: BSWImpl6_Com end */
   {
      /* Box: SWCI17 begin */
      /* Box: populateTask begin */
      SampleAppB_Runnable_Implicit();
      /* Box: populateTask end */
      /* Box: SWCI17 end */
   }
   /* Box: Implicit Buffer Flush begin */
   /* Box: Implicit Buffer Flush end */
   if ( Rte_RECount_OsTask_100ms_divby10_0 != ((VAR(uint8, AUTOMATIC))0U) )
   {
      Rte_RECount_OsTask_100ms_divby10_0--;
   }
   else
   {
      Rte_RECount_OsTask_100ms_divby10_0 = ((VAR(uint8, AUTOMATIC))9);
   }
   TerminateTask();
} /* OsTask_100ms */
#define OS_STOP_SEC_CODE_OSTASK_100MS
#include "Os_MemMap.h"

