/** @file     OsTask_10ms.c
  *
  * @brief    Task OsTask_10ms body
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE for Windows
  * @note     Version 12.5.0
  */

#define RTE_CORE

#include "Rte_Const.h"
#if !defined(RTE_VENDOR_MODE)
#pragma message "Compiling an individual task file but RTE_VENDOR_MODE not defined. Compiling a stale file?"
#endif /* !defined(RTE_VENDOR_MODE) */
#if defined(RTE_USE_TASK_HEADER)
#include "OsTask_10ms.h"
#else /* !defined(RTE_USE_TASK_HEADER) */
#include "Os.h"
#endif /* !defined(RTE_USE_TASK_HEADER) */
#if defined(RTE_REQUIRES_IOC)
#include "Ioc.h"
#endif /* defined(RTE_REQUIRES_IOC) */
#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_Type.h"
#include "Rte_DataHandleType.h"
#include "Rte_ComM.h"
#include "Rte_NvM.h"
#include "Rte_Dem.h"
#include "Rte_FiM.h"
#include "Rte_Dcm.h"
#include "Rte_WdgM.h"
#include "Rte_MemorySWC.h"
#include "Rte_DiagnosticSWC.h"
#include "Rte_T1.h"
#include "Rte_SampleAppA.h"
#include "Rte_SampleAppB.h"

#define RTE_ECUCPARTITION_0_START_SEC_VAR_CLEARED_32
#include "Rte_MemMap.h"
extern VAR(Rte_EcucPartition_0_ImplicitBufsType, RTE_DATA) Rte_EcucPartition_0_ImplicitBufs;
extern VAR(SampleApp_1kB_ArrayType, RTE_DATA) Rte_Rx_000016;
extern VAR(SampleApp_1kB_ArrayType, RTE_DATA) Rte_Rx_000017;
extern VAR(SampleApp_1kB_ArrayType, RTE_DATA) Rte_Rx_000018;
extern VAR(SampleApp_1kB_ArrayType, RTE_DATA) Rte_Rx_000019;
extern VAR(SampleApp_1kB_ArrayType, RTE_DATA) Rte_Rx_000020;
extern VAR(SampleApp_1kB_ArrayType, RTE_DATA) Rte_Rx_000021;
extern VAR(SampleApp_1kB_ArrayType, RTE_DATA) Rte_Rx_000022;
extern VAR(SampleApp_1kB_ArrayType, RTE_DATA) Rte_Rx_000023;
extern VAR(SampleApp_1kB_ArrayType, RTE_DATA) Rte_Rx_000024;
extern VAR(SampleApp_1kB_ArrayType, RTE_DATA) Rte_Rx_000025;
extern VAR(SampleApp_StructureType, RTE_DATA) Rte_Rx_000036;
extern VAR(SampleApp_StructureType, RTE_DATA) Rte_Rx_000037;
extern VAR(SampleApp_StructureType, RTE_DATA) Rte_Rx_000038;
extern VAR(SampleApp_StructureType, RTE_DATA) Rte_Rx_000039;
extern VAR(SampleApp_StructureType, RTE_DATA) Rte_Rx_000040;
extern VAR(SampleApp_StructureType, RTE_DATA) Rte_Rx_000041;
extern VAR(SampleApp_StructureType, RTE_DATA) Rte_Rx_000042;
extern VAR(SampleApp_StructureType, RTE_DATA) Rte_Rx_000043;
extern VAR(SampleApp_StructureType, RTE_DATA) Rte_Rx_000044;
extern VAR(SampleApp_StructureType, RTE_DATA) Rte_Rx_000045;
#define RTE_ECUCPARTITION_0_STOP_SEC_VAR_CLEARED_32
#include "Rte_MemMap.h"

#define RTE_ECUCPARTITION_0_START_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"
extern VAR(uint8, RTE_DATA) Rte_Rx_000011;
extern VAR(uint8, RTE_DATA) Rte_Rx_000026;
extern VAR(uint8, RTE_DATA) Rte_Rx_000027;
extern VAR(uint8, RTE_DATA) Rte_Rx_000028;
extern VAR(uint8, RTE_DATA) Rte_Rx_000029;
extern VAR(uint8, RTE_DATA) Rte_Rx_000030;
extern VAR(uint8, RTE_DATA) Rte_Rx_000031;
extern VAR(uint8, RTE_DATA) Rte_Rx_000032;
extern VAR(uint8, RTE_DATA) Rte_Rx_000033;
extern VAR(uint8, RTE_DATA) Rte_Rx_000034;
extern VAR(uint8, RTE_DATA) Rte_Rx_000035;
#define RTE_ECUCPARTITION_0_STOP_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"

#define BSWM_START_SEC_CODE
#include "BswM_MemMap.h"
/* Runnable entity prototypes */
FUNC(void, BSWM_CODE) BswM_MainFunction(void);
#define BSWM_STOP_SEC_CODE
#include "BswM_MemMap.h"
#define CANSM_START_SEC_CODE
#include "CanSM_MemMap.h"
/* Runnable entity prototypes */
FUNC(void, CANSM_CODE) CanSM_MainFunction(void);
#define CANSM_STOP_SEC_CODE
#include "CanSM_MemMap.h"
#define CAN_START_SEC_CODE
#include "Can_MemMap.h"
/* Runnable entity prototypes */
FUNC(void, CAN_CODE) Can_MainFunction_Read(void);
FUNC(void, CAN_CODE) Can_MainFunction_Write(void);
#define CAN_STOP_SEC_CODE
#include "Can_MemMap.h"
#define COMM_START_SEC_CODE
#include "ComM_MemMap.h"
/* Runnable entity prototypes */
FUNC(void, COMM_CODE) ComM_MainFunction_Can_Network_Channel_Can_Network(void);
FUNC(void, COMM_CODE) ComM_MainFunction_EthernetPhysicalChannel_EthernetCluster(void);
#define COMM_STOP_SEC_CODE
#include "ComM_MemMap.h"
#define COM_START_SEC_CODE
#include "Com_MemMap.h"
/* Runnable entity prototypes */
FUNC(void, COM_CODE) Com_MainFunctionRx_ComMainFunctionRx(void);
#define COM_STOP_SEC_CODE
#include "Com_MemMap.h"
#define DCM_START_SEC_CODE
#include "Dcm_MemMap.h"
/* Runnable entity prototypes */
FUNC(void, DCM_CODE) Dcm_MainFunction(void);
#define DCM_STOP_SEC_CODE
#include "Dcm_MemMap.h"
#define DEM_START_SEC_CODE
#include "Dem_MemMap.h"
/* Runnable entity prototypes */
FUNC(void, DEM_CODE) Dem_MainFunction(void);
#define DEM_STOP_SEC_CODE
#include "Dem_MemMap.h"
#define ECUM_START_SEC_CODE
#include "EcuM_MemMap.h"
/* Runnable entity prototypes */
FUNC(void, ECUM_CODE) EcuM_MainFunction(void);
#define ECUM_STOP_SEC_CODE
#include "EcuM_MemMap.h"
#define ETH_17_GEthMacV2_START_SEC_CODE
#include "Eth_17_GEthMacV2_MemMap.h"
/* Runnable entity prototypes */
FUNC(void, ETH_17_GEthMacV2_CODE) Eth_17_GEthMacV2_MainFunction(void);
#define ETH_17_GEthMacV2_STOP_SEC_CODE
#include "Eth_17_GEthMacV2_MemMap.h"
#define FIM_START_SEC_CODE
#include "FiM_MemMap.h"
/* Runnable entity prototypes */
FUNC(void, FIM_CODE) FiM_MainFunction(void);
#define FIM_STOP_SEC_CODE
#include "FiM_MemMap.h"
#define FLS_START_SEC_CODE
#include "Fls_MemMap.h"
/* Runnable entity prototypes */
FUNC(void, FLS_CODE) Fls_MainFunction(void);
#define FLS_STOP_SEC_CODE
#include "Fls_MemMap.h"
#define MEMIF_START_SEC_CODE
#include "MemIf_MemMap.h"
/* Runnable entity prototypes */
FUNC(void, MEMIF_CODE) MemIf_Rb_MainFunction(void);
#define MEMIF_STOP_SEC_CODE
#include "MemIf_MemMap.h"
#define NVM_START_SEC_CODE
#include "NvM_MemMap.h"
/* Runnable entity prototypes */
FUNC(void, NVM_CODE) NvM_MainFunction(void);
#define NVM_STOP_SEC_CODE
#include "NvM_MemMap.h"
#define T1_START_SEC_CODE
#include "T1_MemMap.h"
/* Runnable entity prototypes */
FUNC(void, T1_CODE) T1_MainFunction(void);
#define T1_STOP_SEC_CODE
#include "T1_MemMap.h"
#define WDGM_START_SEC_CODE
#include "WdgM_MemMap.h"
/* Runnable entity prototypes */
FUNC(void, WDGM_CODE) WdgM_MainFunction_0(void);
#define WDGM_STOP_SEC_CODE
#include "WdgM_MemMap.h"

#define OS_START_SEC_CODE_OSTASK_10MS
#include "Os_MemMap.h"
TASK(OsTask_10ms)
{
   /* Box: Implicit Buffer Initialization begin */
   /* Pre-fill of write buffer */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf1.value = Rte_Rx_000026;
   /* Pre-fill of write buffer */
   Rte_memcpy(Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf2.value, Rte_Rx_000016, sizeof(SampleApp_1kB_ArrayType));
   /* Pre-fill of write buffer */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf3.value = Rte_Rx_000036;
   /* Pre-fill of write buffer */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf4.value = Rte_Rx_000028;
   /* Pre-fill of write buffer */
   Rte_memcpy(Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf5.value, Rte_Rx_000018, sizeof(SampleApp_1kB_ArrayType));
   /* Pre-fill of write buffer */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf6.value = Rte_Rx_000038;
   /* Pre-fill of write buffer */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf7.value = Rte_Rx_000029;
   /* Pre-fill of write buffer */
   Rte_memcpy(Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf8.value, Rte_Rx_000019, sizeof(SampleApp_1kB_ArrayType));
   /* Pre-fill of write buffer */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf9.value = Rte_Rx_000039;
   /* Pre-fill of write buffer */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf10.value = Rte_Rx_000030;
   /* Pre-fill of write buffer */
   Rte_memcpy(Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf11.value, Rte_Rx_000020, sizeof(SampleApp_1kB_ArrayType));
   /* Pre-fill of write buffer */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf12.value = Rte_Rx_000040;
   /* Pre-fill of write buffer */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf13.value = Rte_Rx_000031;
   /* Pre-fill of write buffer */
   Rte_memcpy(Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf14.value, Rte_Rx_000021, sizeof(SampleApp_1kB_ArrayType));
   /* Pre-fill of write buffer */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf15.value = Rte_Rx_000041;
   /* Pre-fill of write buffer */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf16.value = Rte_Rx_000032;
   /* Pre-fill of write buffer */
   Rte_memcpy(Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf17.value, Rte_Rx_000022, sizeof(SampleApp_1kB_ArrayType));
   /* Pre-fill of write buffer */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf18.value = Rte_Rx_000042;
   /* Pre-fill of write buffer */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf19.value = Rte_Rx_000033;
   /* Pre-fill of write buffer */
   Rte_memcpy(Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf20.value, Rte_Rx_000023, sizeof(SampleApp_1kB_ArrayType));
   /* Pre-fill of write buffer */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf21.value = Rte_Rx_000043;
   /* Pre-fill of write buffer */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf22.value = Rte_Rx_000034;
   /* Pre-fill of write buffer */
   Rte_memcpy(Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf23.value, Rte_Rx_000024, sizeof(SampleApp_1kB_ArrayType));
   /* Pre-fill of write buffer */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf24.value = Rte_Rx_000044;
   /* Pre-fill of write buffer */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf25.value = Rte_Rx_000035;
   /* Pre-fill of write buffer */
   Rte_memcpy(Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf26.value, Rte_Rx_000025, sizeof(SampleApp_1kB_ArrayType));
   /* Pre-fill of write buffer */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf27.value = Rte_Rx_000045;
   /* Pre-fill of write buffer */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf28.value = Rte_Rx_000027;
   /* Pre-fill of write buffer */
   Rte_memcpy(Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf29.value, Rte_Rx_000017, sizeof(SampleApp_1kB_ArrayType));
   /* Pre-fill of write buffer */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf30.value = Rte_Rx_000037;
   /* Box: Implicit Buffer Initialization end */
   /* Box: Implicit Buffer Fill begin */
   Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.rbuf0.value = Rte_Rx_000011;
   /* Box: Implicit Buffer Fill end */
   {
      /* Box: BSWImpl9_EcuM begin */
      /* Box: populateTask begin */
      EcuM_MainFunction();
      /* Box: populateTask end */
      /* Box: BSWImpl9_EcuM end */
   }
   {
      /* Box: BSWImpl5_BSWIMPL_BswM begin */
      /* Box: populateTask begin */
      BswM_MainFunction();
      /* Box: populateTask end */
      /* Box: BSWImpl5_BSWIMPL_BswM end */
   }
   {
      /* Box: BSWImpl8_ComM begin */
      /* Box: populateTask begin */
      ComM_MainFunction_EthernetPhysicalChannel_EthernetCluster();
      /* Box: populateTask end */
      /* Box: BSWImpl8_ComM end */
   }
   {
      /* Box: BSWImpl8_ComM begin */
      /* Box: populateTask begin */
      ComM_MainFunction_Can_Network_Channel_Can_Network();
      /* Box: populateTask end */
      /* Box: BSWImpl8_ComM end */
   }
   {
      /* Box: BSWImpl7_CanSM begin */
      /* Box: populateTask begin */
      CanSM_MainFunction();
      /* Box: populateTask end */
      /* Box: BSWImpl7_CanSM end */
   }
   {
      /* Box: BSWImpl1_BSWIMPL_Can begin */
      /* Box: populateTask begin */
      Can_MainFunction_Write();
      /* Box: populateTask end */
      /* Box: BSWImpl1_BSWIMPL_Can end */
   }
   {
      /* Box: BSWImpl1_BSWIMPL_Can begin */
      /* Box: populateTask begin */
      Can_MainFunction_Read();
      /* Box: populateTask end */
      /* Box: BSWImpl1_BSWIMPL_Can end */
   }
   {
      /* Box: BSWImpl6_Com begin */
      /* Box: populateTask begin */
      Com_MainFunctionRx_ComMainFunctionRx();
      /* Box: populateTask end */
      /* Box: BSWImpl6_Com end */
   }
   {
      /* Box: BSWImpl0_Fls begin */
      /* Box: populateTask begin */
      Fls_MainFunction();
      /* Box: populateTask end */
      /* Box: BSWImpl0_Fls end */
   }
   {
      /* Box: BSWImpl17_NvM begin */
      /* Box: populateTask begin */
      NvM_MainFunction();
      /* Box: populateTask end */
      /* Box: BSWImpl17_NvM end */
   }
   {
      /* Box: BSWImpl18_MemIf begin */
      /* Box: populateTask begin */
      MemIf_Rb_MainFunction();
      /* Box: populateTask end */
      /* Box: BSWImpl18_MemIf end */
   }
   {
      /* Box: BSWImpl15_Dem begin */
      /* Box: populateTask begin */
      Dem_MainFunction();
      /* Box: populateTask end */
      /* Box: BSWImpl15_Dem end */
   }
   {
      /* Box: BSWImpl12_BSWIMPL_FiM begin */
      /* Box: populateTask begin */
      FiM_MainFunction();
      /* Box: populateTask end */
      /* Box: BSWImpl12_BSWIMPL_FiM end */
   }
   {
      /* Box: BSWImpl13_Dcm begin */
      /* Box: populateTask begin */
      Dcm_MainFunction();
      /* Box: populateTask end */
      /* Box: BSWImpl13_Dcm end */
   }
   {
      /* Box: BSWImpl16_WdgM begin */
      /* Box: populateTask begin */
      WdgM_MainFunction_0();
      /* Box: populateTask end */
      /* Box: BSWImpl16_WdgM end */
   }
   {
      /* Box: CPT_MemorySWC begin */
      /* Box: populateTask begin */
      RE_MemSWC();
      /* Box: populateTask end */
      /* Box: CPT_MemorySWC end */
   }
   {
      /* Box: CPT_DiagnosticSWC begin */
      /* Box: populateTask begin */
      RE_Dem_Periodic();
      /* Box: populateTask end */
      /* Box: CPT_DiagnosticSWC end */
   }
   {
      /* Box: CPT_DiagnosticSWC begin */
      /* Box: populateTask begin */
      RE_Diag_Periodic();
      /* Box: populateTask end */
      /* Box: CPT_DiagnosticSWC end */
   }
   {
      /* Box: BSWImpl2_Eth begin */
      /* Box: populateTask begin */
      Eth_17_GEthMacV2_MainFunction();
      /* Box: populateTask end */
      /* Box: BSWImpl2_Eth end */
   }
   {
      /* Box: BSWImpl4_T1_BswImpl begin */
      /* Box: populateTask begin */
      T1_MainFunction();
      /* Box: populateTask end */
      /* Box: BSWImpl4_T1_BswImpl end */
   }
   {
      /* Box: SWCI16 begin */
      /* Box: populateTask begin */
      SampleAppA_Runnable_Implicit();
      /* Box: populateTask end */
      /* Box: SWCI16 end */
   }
   {
      /* Box: SWCI16 begin */
      /* Box: populateTask begin */
      SampleAppA_Runnable_Explicit();
      /* Box: populateTask end */
      /* Box: SWCI16 end */
   }
   {
      /* Box: SWCI17 begin */
      /* Box: populateTask begin */
      SampleAppB_Runnable_Explicit();
      /* Box: populateTask end */
      /* Box: SWCI17 end */
   }
   /* Box: Implicit Buffer Flush begin */
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_1byte/byteData in port /SwComponentTypes/SampleAppB/SR_Implicit_1byte_1 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_Rx_000026 = Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf1.value;
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_1024byte/arrayData in port /SwComponentTypes/SampleAppB/SR_Implicit_1024byte_1 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_memcpy(Rte_Rx_000016, Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf2.value, sizeof(SampleApp_1kB_ArrayType));
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_Structure/sampleStructure in port /SwComponentTypes/SampleAppB/SR_Structure_1 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_Rx_000036 = Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf3.value;
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_1byte/byteData in port /SwComponentTypes/SampleAppB/SR_Implicit_1byte_2 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_Rx_000028 = Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf4.value;
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_1024byte/arrayData in port /SwComponentTypes/SampleAppB/SR_Implicit_1024byte_2 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_memcpy(Rte_Rx_000018, Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf5.value, sizeof(SampleApp_1kB_ArrayType));
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_Structure/sampleStructure in port /SwComponentTypes/SampleAppB/SR_Structure_2 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_Rx_000038 = Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf6.value;
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_1byte/byteData in port /SwComponentTypes/SampleAppB/SR_Implicit_1byte_3 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_Rx_000029 = Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf7.value;
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_1024byte/arrayData in port /SwComponentTypes/SampleAppB/SR_Implicit_1024byte_3 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_memcpy(Rte_Rx_000019, Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf8.value, sizeof(SampleApp_1kB_ArrayType));
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_Structure/sampleStructure in port /SwComponentTypes/SampleAppB/SR_Structure_3 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_Rx_000039 = Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf9.value;
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_1byte/byteData in port /SwComponentTypes/SampleAppB/SR_Implicit_1byte_4 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_Rx_000030 = Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf10.value;
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_1024byte/arrayData in port /SwComponentTypes/SampleAppB/SR_Implicit_1024byte_4 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_memcpy(Rte_Rx_000020, Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf11.value, sizeof(SampleApp_1kB_ArrayType));
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_Structure/sampleStructure in port /SwComponentTypes/SampleAppB/SR_Structure_4 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_Rx_000040 = Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf12.value;
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_1byte/byteData in port /SwComponentTypes/SampleAppB/SR_Implicit_1byte_5 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_Rx_000031 = Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf13.value;
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_1024byte/arrayData in port /SwComponentTypes/SampleAppB/SR_Implicit_1024byte_5 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_memcpy(Rte_Rx_000021, Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf14.value, sizeof(SampleApp_1kB_ArrayType));
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_Structure/sampleStructure in port /SwComponentTypes/SampleAppB/SR_Structure_5 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_Rx_000041 = Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf15.value;
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_1byte/byteData in port /SwComponentTypes/SampleAppB/SR_Implicit_1byte_6 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_Rx_000032 = Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf16.value;
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_1024byte/arrayData in port /SwComponentTypes/SampleAppB/SR_Implicit_1024byte_6 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_memcpy(Rte_Rx_000022, Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf17.value, sizeof(SampleApp_1kB_ArrayType));
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_Structure/sampleStructure in port /SwComponentTypes/SampleAppB/SR_Structure_6 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_Rx_000042 = Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf18.value;
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_1byte/byteData in port /SwComponentTypes/SampleAppB/SR_Implicit_1byte_7 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_Rx_000033 = Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf19.value;
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_1024byte/arrayData in port /SwComponentTypes/SampleAppB/SR_Implicit_1024byte_7 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_memcpy(Rte_Rx_000023, Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf20.value, sizeof(SampleApp_1kB_ArrayType));
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_Structure/sampleStructure in port /SwComponentTypes/SampleAppB/SR_Structure_7 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_Rx_000043 = Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf21.value;
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_1byte/byteData in port /SwComponentTypes/SampleAppB/SR_Implicit_1byte_8 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_Rx_000034 = Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf22.value;
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_1024byte/arrayData in port /SwComponentTypes/SampleAppB/SR_Implicit_1024byte_8 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_memcpy(Rte_Rx_000024, Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf23.value, sizeof(SampleApp_1kB_ArrayType));
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_Structure/sampleStructure in port /SwComponentTypes/SampleAppB/SR_Structure_8 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_Rx_000044 = Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf24.value;
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_1byte/byteData in port /SwComponentTypes/SampleAppB/SR_Implicit_1byte_9 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_Rx_000035 = Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf25.value;
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_1024byte/arrayData in port /SwComponentTypes/SampleAppB/SR_Implicit_1024byte_9 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_memcpy(Rte_Rx_000025, Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf26.value, sizeof(SampleApp_1kB_ArrayType));
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_Structure/sampleStructure in port /SwComponentTypes/SampleAppB/SR_Structure_9 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_Rx_000045 = Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf27.value;
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_1byte/byteData in port /SwComponentTypes/SampleAppB/SR_Implicit_1byte_10 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_Rx_000027 = Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf28.value;
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_1024byte/arrayData in port /SwComponentTypes/SampleAppB/SR_Implicit_1024byte_10 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_memcpy(Rte_Rx_000017, Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf29.value, sizeof(SampleApp_1kB_ArrayType));
   /* Write to Sender-Receiver DataItem /Interfaces/SampleApp_SR_IF_Structure/sampleStructure in port /SwComponentTypes/SampleAppB/SR_Structure_10 on Application Software Component Instance /ApplicationECU_FlatView/SwComponentTypes/ApplicationECU_FlatView/CPT_SampleAppB */
   Rte_Rx_000037 = Rte_EcucPartition_0_ImplicitBufs.isa_Core0_9.Rte_OsTask_10ms.wbuf30.value;
   /* Box: Implicit Buffer Flush end */
   TerminateTask();
} /* OsTask_10ms */
#define OS_STOP_SEC_CODE_OSTASK_10MS
#include "Os_MemMap.h"

